# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sanityTestVisualEd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bredvidnoacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2a3f30cdbffb4b128da835679a05b60d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9f755887585c477397b8aa89415cd2a5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bredvidnoacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2a3f30cdbffb4b128da835679a05b60d }}/test-visualed:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sanityTestVisualEd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_135066cce7f44365a2291a2571c23e39 }}
        images: 'bredvidnoacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2a3f30cdbffb4b128da835679a05b60d }}/test-visualed:${{ github.sha }}'